// ReportsStore.js — Sales Manager Reports Module (Teams, TLs, Executives)
// No self-report data included.

// ─────────────────────────────────────────────────────────────────────────────
// OVERVIEW — KPI Cards
// ─────────────────────────────────────────────────────────────────────────────
export const overviewKPIs = [
  { title: "Total Leads",          value: "2,480", accent: "#3b82f6" },
  { title: "Total Calls",          value: "4,820", accent: "#14b8a6" },
  { title: "Total Prospects",      value: "892",   accent: "#8b5cf6" },
  { title: "Total Sales",          value: "374",   accent: "#22c55e" },
  { title: "Total Revenue",        value: "₹18.4L", accent: "#f59e0b" },
  { title: "Dump Leads",           value: "312",   accent: "#f43f5e" },
  { title: "Missed Follow-ups",    value: "148",   accent: "#ef4444" },
  { title: "Conversion Rate",      value: "15.1%", accent: "#10b981" },
];

// ─────────────────────────────────────────────────────────────────────────────
// OVERVIEW — Charts
// ─────────────────────────────────────────────────────────────────────────────

// Calls vs Sales — weekly (GLineChart)
export const callsVsSalesData = [
  { name: "Mon", calls: 162, sales: 14 },
  { name: "Tue", calls: 198, sales: 22 },
  { name: "Wed", calls: 145, sales: 11 },
  { name: "Thu", calls: 221, sales: 28 },
  { name: "Fri", calls: 186, sales: 21 },
  { name: "Sat", calls: 98,  sales: 8  },
];

// Leads vs Prospects — weekly (GLineChart)
export const leadsVsProspectsData = [
  { name: "Mon", leads: 420, prospects: 68 },
  { name: "Tue", leads: 510, prospects: 92 },
  { name: "Wed", leads: 380, prospects: 55 },
  { name: "Thu", leads: 590, prospects: 118 },
  { name: "Fri", leads: 470, prospects: 88 },
  { name: "Sat", leads: 210, prospects: 34 },
];

// Revenue Trend — monthly (GColumnChart)
export const revenueTrendData = [
  { name: "Jan", revenue: 1240000 },
  { name: "Feb", revenue: 1480000 },
  { name: "Mar", revenue: 1720000 },
  { name: "Apr", revenue: 1560000 },
  { name: "May", revenue: 1840000 },
];

// Team Performance Comparison (GColumnChart)
export const teamPerfCompData = [
  { name: "Team Alpha", calls: 1300, prospects: 280, sales: 102, revenue: 612000 },
  { name: "Team Beta",  calls: 1140, prospects: 232, sales: 88,  revenue: 528000 },
  { name: "Team Gamma", calls: 1520, prospects: 310, sales: 124, revenue: 744000 },
];

// Lead Status Breakdown (GDoughnutChart)
export const leadStatusData = [
  { name: "Converted",   value: 374 },
  { name: "Prospect",    value: 892 },
  { name: "Follow-up",   value: 648 },
  { name: "In Progress", value: 354 },
  { name: "Dump",        value: 312 },
  { name: "New",         value: 523 },
];
export const leadStatusColors = ["#22c55e","#8b5cf6","#3b82f6","#14b8a6","#f43f5e","#f59e0b"];

// ─────────────────────────────────────────────────────────────────────────────
// TEAM REPORTS
// ─────────────────────────────────────────────────────────────────────────────
export const teamReportRows = [
  {
    id: "TR001",
    teamName:       "Team Alpha",
    teamLeader:     "Ankit Verma",
    totalExec:      4,
    assignedLeads:  820,
    completedCalls: 1300,
    prospects:      280,
    sales:          102,
    dumpLeads:      98,
    missedFollowups:32,
    revenue:        "₹6,12,000",
    conversion:     "12.4%",
    status:         "Active",
  },
  {
    id: "TR002",
    teamName:       "Team Beta",
    teamLeader:     "Sonal Gupta",
    totalExec:      4,
    assignedLeads:  740,
    completedCalls: 1140,
    prospects:      232,
    sales:          88,
    dumpLeads:      112,
    missedFollowups:41,
    revenue:        "₹5,28,000",
    conversion:     "11.9%",
    status:         "Active",
  },
  {
    id: "TR003",
    teamName:       "Team Gamma",
    teamLeader:     "Nisha Patel",
    totalExec:      4,
    assignedLeads:  920,
    completedCalls: 1520,
    prospects:      310,
    sales:          124,
    dumpLeads:      102,
    missedFollowups:28,
    revenue:        "₹7,44,000",
    conversion:     "13.5%",
    status:         "Active",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// TEAM LEADER REPORTS
// ─────────────────────────────────────────────────────────────────────────────
export const tlReportRows = [
  {
    id: "TL001",
    tlName:         "Ankit Verma",
    teamName:       "Team Alpha",
    assignedLeads:  820,
    completedCalls: 1300,
    prospects:      280,
    sales:          102,
    dumpLeads:      98,
    missedFollowups:32,
    revenue:        "₹6,12,000",
    target:         "₹7,00,000",
    achieved:       "87.4%",
    conversion:     "12.4%",
    status:         "Active",
  },
  {
    id: "TL002",
    tlName:         "Sonal Gupta",
    teamName:       "Team Beta",
    assignedLeads:  740,
    completedCalls: 1140,
    prospects:      232,
    sales:          88,
    dumpLeads:      112,
    missedFollowups:41,
    revenue:        "₹5,28,000",
    target:         "₹6,50,000",
    achieved:       "81.2%",
    conversion:     "11.9%",
    status:         "Active",
  },
  {
    id: "TL003",
    tlName:         "Nisha Patel",
    teamName:       "Team Gamma",
    assignedLeads:  920,
    completedCalls: 1520,
    prospects:      310,
    sales:          124,
    dumpLeads:      102,
    missedFollowups:28,
    revenue:        "₹7,44,000",
    target:         "₹7,50,000",
    achieved:       "99.2%",
    conversion:     "13.5%",
    status:         "Active",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXECUTIVE REPORTS
// ─────────────────────────────────────────────────────────────────────────────
export const execReportRows = [
  // Team Alpha
  {
    id: "EX001",
    execName:       "Rahul Sharma",
    teamLeader:     "Ankit Verma",
    teamName:       "Team Alpha",
    assignedLeads:  210,
    completedCalls: 420,
    talk:           380,
    notTalk:        40,
    interested:     95,
    prospects:      72,
    sales:          28,
    dumpLeads:      24,
    missedFollowups:8,
    revenue:        "₹1,68,000",
    conversion:     "13.3%",
    status:         "Active",
  },
  {
    id: "EX002",
    execName:       "Priya Mehta",
    teamLeader:     "Ankit Verma",
    teamName:       "Team Alpha",
    assignedLeads:  195,
    completedCalls: 380,
    talk:           340,
    notTalk:        40,
    interested:     82,
    prospects:      64,
    sales:          24,
    dumpLeads:      28,
    missedFollowups:10,
    revenue:        "₹1,44,000",
    conversion:     "12.3%",
    status:         "Active",
  },
  {
    id: "EX003",
    execName:       "Vikram Tiwari",
    teamLeader:     "Ankit Verma",
    teamName:       "Team Alpha",
    assignedLeads:  220,
    completedCalls: 260,
    talk:           220,
    notTalk:        40,
    interested:     68,
    prospects:      82,
    sales:          30,
    dumpLeads:      22,
    missedFollowups:7,
    revenue:        "₹1,80,000",
    conversion:     "13.6%",
    status:         "Active",
  },
  {
    id: "EX004",
    execName:       "Divya Nair",
    teamLeader:     "Ankit Verma",
    teamName:       "Team Alpha",
    assignedLeads:  195,
    completedCalls: 240,
    talk:           200,
    notTalk:        40,
    interested:     55,
    prospects:      62,
    sales:          20,
    dumpLeads:      24,
    missedFollowups:7,
    revenue:        "₹1,20,000",
    conversion:     "10.3%",
    status:         "Active",
  },
  // Team Beta
  {
    id: "EX005",
    execName:       "Arjun Kapoor",
    teamLeader:     "Sonal Gupta",
    teamName:       "Team Beta",
    assignedLeads:  200,
    completedCalls: 310,
    talk:           270,
    notTalk:        40,
    interested:     72,
    prospects:      68,
    sales:          26,
    dumpLeads:      30,
    missedFollowups:12,
    revenue:        "₹1,56,000",
    conversion:     "13.0%",
    status:         "Active",
  },
  {
    id: "EX006",
    execName:       "Sneha Rajput",
    teamLeader:     "Sonal Gupta",
    teamName:       "Team Beta",
    assignedLeads:  180,
    completedCalls: 290,
    talk:           250,
    notTalk:        40,
    interested:     58,
    prospects:      52,
    sales:          18,
    dumpLeads:      32,
    missedFollowups:14,
    revenue:        "₹1,08,000",
    conversion:     "10.0%",
    status:         "Active",
  },
  {
    id: "EX007",
    execName:       "Mohit Joshi",
    teamLeader:     "Sonal Gupta",
    teamName:       "Team Beta",
    assignedLeads:  185,
    completedCalls: 280,
    talk:           240,
    notTalk:        40,
    interested:     62,
    prospects:      58,
    sales:          22,
    dumpLeads:      28,
    missedFollowups:9,
    revenue:        "₹1,32,000",
    conversion:     "11.9%",
    status:         "Active",
  },
  {
    id: "EX008",
    execName:       "Kavya Patel",
    teamLeader:     "Sonal Gupta",
    teamName:       "Team Beta",
    assignedLeads:  175,
    completedCalls: 260,
    talk:           220,
    notTalk:        40,
    interested:     54,
    prospects:      54,
    sales:          22,
    dumpLeads:      22,
    missedFollowups:6,
    revenue:        "₹1,32,000",
    conversion:     "12.6%",
    status:         "Active",
  },
  // Team Gamma
  {
    id: "EX009",
    execName:       "Rahul Verma",
    teamLeader:     "Nisha Patel",
    teamName:       "Team Gamma",
    assignedLeads:  240,
    completedCalls: 420,
    talk:           380,
    notTalk:        40,
    interested:     98,
    prospects:      88,
    sales:          34,
    dumpLeads:      26,
    missedFollowups:7,
    revenue:        "₹2,04,000",
    conversion:     "14.2%",
    status:         "Active",
  },
  {
    id: "EX010",
    execName:       "Pooja Sharma",
    teamLeader:     "Nisha Patel",
    teamName:       "Team Gamma",
    assignedLeads:  230,
    completedCalls: 390,
    talk:           350,
    notTalk:        40,
    interested:     88,
    prospects:      78,
    sales:          30,
    dumpLeads:      28,
    missedFollowups:8,
    revenue:        "₹1,80,000",
    conversion:     "13.0%",
    status:         "Active",
  },
  {
    id: "EX011",
    execName:       "Suresh Menon",
    teamLeader:     "Nisha Patel",
    teamName:       "Team Gamma",
    assignedLeads:  225,
    completedCalls: 360,
    talk:           320,
    notTalk:        40,
    interested:     78,
    prospects:      72,
    sales:          30,
    dumpLeads:      24,
    missedFollowups:7,
    revenue:        "₹1,80,000",
    conversion:     "13.3%",
    status:         "Active",
  },
  {
    id: "EX012",
    execName:       "Anjali Rao",
    teamLeader:     "Nisha Patel",
    teamName:       "Team Gamma",
    assignedLeads:  225,
    completedCalls: 350,
    talk:           310,
    notTalk:        40,
    interested:     72,
    prospects:      72,
    sales:          30,
    dumpLeads:      24,
    missedFollowups:6,
    revenue:        "₹1,80,000",
    conversion:     "13.3%",
    status:         "Active",
  },
];
