// EmployeeStore.js — dummy employee data for Sales Manager

export const employeeRows = [
  {
    id: "EMP001",
    name: "Rahul Sharma",
    role: "Executive",
    teamLeader: "Ankit Verma",
    teamName: "Team Alpha",
    email: "rahul.sharma@crm.in",
    mobile: "9876543210",
    joinDate: "2024-01-15",
    status: "Active",
    avatar: "RS",
    totalLeads: 420,
    totalCalls: 1240,
    totalSales: 58,
    revenue: "₹3,48,000",
    conversion: "13.8%",
    address: "Mumbai, Maharashtra",
    dob: "1998-06-12",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP002",
    name: "Priya Mehta",
    role: "Executive",
    teamLeader: "Ankit Verma",
    teamName: "Team Alpha",
    email: "priya.mehta@crm.in",
    mobile: "9123456789",
    joinDate: "2024-02-20",
    status: "Active",
    avatar: "PM",
    totalLeads: 380,
    totalCalls: 1080,
    totalSales: 44,
    revenue: "₹2,64,000",
    conversion: "11.6%",
    address: "Delhi, NCR",
    dob: "1999-03-25",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP003",
    name: "Vikram Tiwari",
    role: "Executive",
    teamLeader: "Ankit Verma",
    teamName: "Team Alpha",
    email: "vikram.tiwari@crm.in",
    mobile: "9988776655",
    joinDate: "2024-03-10",
    status: "Active",
    avatar: "VT",
    totalLeads: 340,
    totalCalls: 980,
    totalSales: 38,
    revenue: "₹2,28,000",
    conversion: "11.2%",
    address: "Chennai, Tamil Nadu",
    dob: "1997-11-08",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP004",
    name: "Divya Nair",
    role: "Executive",
    teamLeader: "Ankit Verma",
    teamName: "Team Alpha",
    email: "divya.nair@crm.in",
    mobile: "8800112233",
    joinDate: "2024-04-05",
    status: "Active",
    avatar: "DN",
    totalLeads: 270,
    totalCalls: 820,
    totalSales: 22,
    revenue: "₹1,32,000",
    conversion: "8.1%",
    address: "Hyderabad, Telangana",
    dob: "2000-07-19",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP005",
    name: "Arjun Kapoor",
    role: "Executive",
    teamLeader: "Sonal Gupta",
    teamName: "Team Beta",
    email: "arjun.kapoor@crm.in",
    mobile: "7765432100",
    joinDate: "2024-01-22",
    status: "Active",
    avatar: "AK",
    totalLeads: 510,
    totalCalls: 1420,
    totalSales: 72,
    revenue: "₹4,32,000",
    conversion: "14.1%",
    address: "Pune, Maharashtra",
    dob: "1996-09-14",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP006",
    name: "Sneha Rajput",
    role: "Executive",
    teamLeader: "Sonal Gupta",
    teamName: "Team Beta",
    email: "sneha.rajput@crm.in",
    mobile: "9001122334",
    joinDate: "2024-05-18",
    status: "Active",
    avatar: "SR",
    totalLeads: 290,
    totalCalls: 860,
    totalSales: 31,
    revenue: "₹1,86,000",
    conversion: "10.7%",
    address: "Jaipur, Rajasthan",
    dob: "1999-12-02",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP007",
    name: "Mohit Joshi",
    role: "Executive",
    teamLeader: "Sonal Gupta",
    teamName: "Team Beta",
    email: "mohit.joshi@crm.in",
    mobile: "8004455667",
    joinDate: "2024-02-14",
    status: "Active",
    avatar: "MJ",
    totalLeads: 310,
    totalCalls: 920,
    totalSales: 29,
    revenue: "₹1,74,000",
    conversion: "9.4%",
    address: "Ahmedabad, Gujarat",
    dob: "1998-04-30",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP008",
    name: "Kavya Patel",
    role: "Executive",
    teamLeader: "Sonal Gupta",
    teamName: "Team Beta",
    email: "kavya.patel@crm.in",
    mobile: "7009988776",
    joinDate: "2024-06-01",
    status: "Inactive",
    avatar: "KP",
    totalLeads: 460,
    totalCalls: 1280,
    totalSales: 65,
    revenue: "₹3,90,000",
    conversion: "14.1%",
    address: "Bangalore, Karnataka",
    dob: "1997-08-22",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP009",
    name: "Rahul Verma",
    role: "Executive",
    teamLeader: "Nisha Patel",
    teamName: "Team Gamma",
    email: "rahul.verma@crm.in",
    mobile: "9812345670",
    joinDate: "2024-03-28",
    status: "Active",
    avatar: "RV",
    totalLeads: 580,
    totalCalls: 1640,
    totalSales: 84,
    revenue: "₹5,04,000",
    conversion: "14.5%",
    address: "Kolkata, West Bengal",
    dob: "1995-02-17",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP010",
    name: "Pooja Sharma",
    role: "Executive",
    teamLeader: "Nisha Patel",
    teamName: "Team Gamma",
    email: "pooja.sharma@crm.in",
    mobile: "9900112233",
    joinDate: "2024-04-12",
    status: "Active",
    avatar: "PS",
    totalLeads: 390,
    totalCalls: 1100,
    totalSales: 48,
    revenue: "₹2,88,000",
    conversion: "12.3%",
    address: "Lucknow, Uttar Pradesh",
    dob: "1999-10-05",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP011",
    name: "Suresh Menon",
    role: "Executive",
    teamLeader: "Nisha Patel",
    teamName: "Team Gamma",
    email: "suresh.menon@crm.in",
    mobile: "8811223344",
    joinDate: "2024-01-08",
    status: "Active",
    avatar: "SM",
    totalLeads: 490,
    totalCalls: 1380,
    totalSales: 68,
    revenue: "₹4,08,000",
    conversion: "13.9%",
    address: "Kochi, Kerala",
    dob: "1996-05-28",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP012",
    name: "Anjali Rao",
    role: "Executive",
    teamLeader: "Nisha Patel",
    teamName: "Team Gamma",
    email: "anjali.rao@crm.in",
    mobile: "9922334455",
    joinDate: "2024-07-15",
    status: "Active",
    avatar: "AR",
    totalLeads: 270,
    totalCalls: 780,
    totalSales: 22,
    revenue: "₹1,32,000",
    conversion: "8.1%",
    address: "Bhopal, Madhya Pradesh",
    dob: "2001-01-14",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  // Team Leaders
  {
    id: "EMP013",
    name: "Ankit Verma",
    role: "Team Leader",
    teamLeader: "Self",
    teamName: "Team Alpha",
    email: "ankit.verma@crm.in",
    mobile: "9811223344",
    joinDate: "2023-06-01",
    status: "Active",
    avatar: "AV",
    totalLeads: 1300,
    totalCalls: 3800,
    totalSales: 102,
    revenue: "₹6,12,000",
    conversion: "12.4%",
    address: "Pune, Maharashtra",
    dob: "1993-07-20",
    gender: "Male",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP014",
    name: "Sonal Gupta",
    role: "Team Leader",
    teamLeader: "Self",
    teamName: "Team Beta",
    email: "sonal.gupta@crm.in",
    mobile: "9700112233",
    joinDate: "2023-07-15",
    status: "Active",
    avatar: "SG",
    totalLeads: 1140,
    totalCalls: 3200,
    totalSales: 88,
    revenue: "₹5,28,000",
    conversion: "11.9%",
    address: "Ahmedabad, Gujarat",
    dob: "1994-03-11",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
  {
    id: "EMP015",
    name: "Nisha Patel",
    role: "Team Leader",
    teamLeader: "Self",
    teamName: "Team Gamma",
    email: "nisha.patel@crm.in",
    mobile: "9600112233",
    joinDate: "2023-08-20",
    status: "Active",
    avatar: "NP",
    totalLeads: 1520,
    totalCalls: 4200,
    totalSales: 124,
    revenue: "₹7,44,000",
    conversion: "13.5%",
    address: "Bangalore, Karnataka",
    dob: "1992-11-30",
    gender: "Female",
    department: "Sales",
    employeeType: "Full-time",
  },
];

export const employeeKPIs = [
  { title: "Total Employees", value: "15",  accent: "#3b82f6" },
  { title: "Team Leaders",    value: "3",   accent: "#8b5cf6" },
  { title: "Executives",      value: "12",  accent: "#14b8a6" },
  { title: "Active",          value: "14",  accent: "#22c55e" },
];
