// paymentsStore.js — TL Payment Alerts (self + team executives)

import { teamExecutives, currentTL } from "../teamLeaderStore";

export const kpiPayments = [
  { title: "Successful (Today)", value: "8",        accent: "#22c55e" },
  { title: "Failed (Today)",     value: "2",        accent: "#f43f5e" },
  { title: "Total Revenue",      value: "₹2.4L",    accent: "#3b82f6" },
  { title: "Pending Verifications", value: "3",     accent: "#f59e0b" },
];

export const paymentAlerts = [
  {
    id: "PAY-1042",
    client: "Rakesh Industries",
    amount: "₹48,000",
    mode: "UPI",
    status: "Success",
    handler: teamExecutives[0].name,
    handlerRole: "Executive",
    date: "2026-05-06",
    time: "10:42 AM",
    txn: "TXN9001A2B",
    note: "Full payment received.",
  },
  {
    id: "PAY-1041",
    client: "Sunrise Traders",
    amount: "₹12,500",
    mode: "Card",
    status: "Failed",
    handler: teamExecutives[2].name,
    handlerRole: "Executive",
    date: "2026-05-06",
    time: "10:18 AM",
    txn: "TXN9001A2A",
    note: "Card declined by issuer.",
  },
  {
    id: "PAY-1040",
    client: "Vimal Logistics",
    amount: "₹36,000",
    mode: "Bank Transfer",
    status: "Success",
    handler: teamExecutives[1].name,
    handlerRole: "Executive",
    date: "2026-05-06",
    time: "09:50 AM",
    txn: "TXN9001A29",
    note: "Partial payment (50%).",
  },
  {
    id: "PAY-1039",
    client: "Karan Enterprises",
    amount: "₹84,000",
    mode: "UPI",
    status: "Success",
    handler: currentTL.name,
    handlerRole: "Team Leader",
    date: "2026-05-06",
    time: "09:32 AM",
    txn: "TXN9001A28",
    note: "Closed by TL.",
  },
  {
    id: "PAY-1038",
    client: "Astra Realty",
    amount: "₹22,000",
    mode: "Card",
    status: "Failed",
    handler: teamExecutives[3].name,
    handlerRole: "Executive",
    date: "2026-05-05",
    time: "06:14 PM",
    txn: "TXN9001A27",
    note: "Insufficient funds.",
  },
  {
    id: "PAY-1037",
    client: "Megabyte Soft",
    amount: "₹1,20,000",
    mode: "Bank Transfer",
    status: "Success",
    handler: teamExecutives[0].name,
    handlerRole: "Executive",
    date: "2026-05-05",
    time: "04:42 PM",
    txn: "TXN9001A26",
    note: "Full payment received.",
  },
  {
    id: "PAY-1036",
    client: "Hindustan Steel",
    amount: "₹66,000",
    mode: "UPI",
    status: "Pending",
    handler: teamExecutives[5].name,
    handlerRole: "Executive",
    date: "2026-05-05",
    time: "02:17 PM",
    txn: "TXN9001A25",
    note: "Awaiting bank confirmation.",
  },
  {
    id: "PAY-1035",
    client: "Greenfield Pvt Ltd",
    amount: "₹52,500",
    mode: "Card",
    status: "Success",
    handler: teamExecutives[1].name,
    handlerRole: "Executive",
    date: "2026-05-05",
    time: "01:08 PM",
    txn: "TXN9001A24",
    note: "Full payment received.",
  },
];
