import { useMemo, useState } from "react";
import {
  BarChart3, CalendarRange, Layers3, Plus, Users, Eye, Pencil,
  FileText, CheckCircle, AlertCircle, Clock, TrendingUp, TrendingDown,
  FileDown,
} from "lucide-react";
import {
  DashGrid, EnhancedDashCard as DashCard, DataTable, Heading,
  PanelModal as Modal, openModal, closeModal, Button,
  Grid, InputField, SelectField, Option, GAreaChart, GBarChart,
} from "../../components/shared/Common_Components";

// ── Mock Data ──────────────────────────────────────────────────────────────

const initialReports = [
  { id: "RPT-300", title: "Daily Sales Activity", type: "Sales", department: "Sales", cadence: "Daily", period: "23 Apr 2026", status: "Published", owner: "Aarav Mehta", generatedOn: "23 Apr 2026, 08:30 AM", summary: "Captures fresh leads, follow-ups completed, and conversion movement across the sales desk.", priority: "Normal" },
  { id: "RPT-301", title: "Monthly Sales Performance", type: "Sales", department: "Sales", cadence: "Monthly", period: "Apr 2026", status: "Published", owner: "Riya Sharma", generatedOn: "19 Apr 2026, 09:20 AM", summary: "Tracks lead conversion, revenue movement, and follow-up performance across regional sales teams.", priority: "Normal" },
  { id: "RPT-302", title: "Finance Collection Overview", type: "Finance", department: "Finance", cadence: "Quarterly", period: "Q2 2026", status: "Draft", owner: "Vikram Nair", generatedOn: "18 Apr 2026, 05:10 PM", summary: "Shows pending invoices, collection trends, and payment delays across active client accounts.", priority: "Critical" },
  { id: "RPT-303", title: "Management Pipeline Snapshot", type: "Executive", department: "Mgmt", cadence: "Weekly", period: "Week 16, 2026", status: "Scheduled", owner: "Ananya Patel", generatedOn: "19 Apr 2026, 08:00 AM", summary: "High-level summary of team delivery, lead pipeline, project health, and escalation trends.", priority: "Normal" },
  { id: "RPT-304", title: "HR Attrition Report", type: "Executive", department: "HR", cadence: "Monthly", period: "Apr 2026", status: "Draft", owner: "Karan Bhatia", generatedOn: "20 Apr 2026, 11:00 AM", summary: "Tracks employee turnover, new hires, and department-level attrition rates.", priority: "Normal" },
];

const reportTrendData = [
  { name: "Jan", published: 5, draft: 2, scheduled: 1 },
  { name: "Feb", published: 7, draft: 3, scheduled: 2 },
  { name: "Mar", published: 6, draft: 1, scheduled: 3 },
  { name: "Apr", published: 9, draft: 4, scheduled: 2 },
  { name: "May", published: 8, draft: 2, scheduled: 1 },
  { name: "Jun", published: 10, draft: 3, scheduled: 2 },
];

const deptReportData = [
  { name: "Sales", reports: 12, approved: 10 },
  { name: "Finance", reports: 8, approved: 5 },
  { name: "Mgmt", reports: 6, approved: 5 },
  { name: "HR", reports: 4, approved: 3 },
];

const defaultForm = { title: "", type: "Sales", department: "Sales", cadence: "Monthly", period: "", owner: "", status: "Draft", summary: "", priority: "Normal" };

const columns = [
  { key: "id", label: "Report ID" },
  { key: "title", label: "Report Name" },
  { key: "department", label: "Department" },
  { key: "owner", label: "Generated By" },
  { key: "type", label: "Type" },
  { key: "priority", label: "Priority" },
  { key: "status", label: "Status" },
  { key: "generatedOn", label: "Last Updated" },
];

// ── Component ──────────────────────────────────────────────────────────────

export default function Report() {
  const [reports, setReports] = useState(initialReports);
  const [activeReport, setActiveReport] = useState(null);
  const [form, setForm] = useState(defaultForm);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // KPIs
  const total = reports.length;
  const published = reports.filter(r => r.status === "Published").length;
  const drafts = reports.filter(r => r.status === "Draft").length;
  const critical = reports.filter(r => r.priority === "Critical").length;

  const handleFormChange = (key, value) => setForm(prev => ({ ...prev, [key]: value }));

  const handleSave = () => {
    if (!form.title.trim() || !form.owner.trim()) return;
    setIsSubmitting(true);
    setTimeout(() => {
      if (form.id) {
        setReports(prev => prev.map(r => r.id === form.id ? { ...form } : r));
      } else {
        const newReport = {
          ...form,
          id: `RPT-${305 + reports.length}`,
          generatedOn: new Date().toLocaleString("en-US", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }),
        };
        setReports(prev => [newReport, ...prev]);
      }
      closeModal("report-form-modal");
      setIsSubmitting(false);
    }, 400);
  };

  const handleDelete = () => {
    setIsSubmitting(true);
    setTimeout(() => {
      setReports(prev => prev.filter(r => r.id !== form.id));
      closeModal("report-form-modal");
      setIsSubmitting(false);
    }, 400);
  };

  const handleExport = () => {
    const headers = columns.map(c => c.label).join(",");
    const rows = reports.map(r => columns.map(c => `"${r[c.key] || ""}"`).join(","));
    const blob = new Blob([headers + "\n" + rows.join("\n")], { type: "text/csv" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "reports-export.csv"; a.click();
  };

  const tableActions = [
    { icon: <Eye size={14} />, tooltip: "View", variant: "ghost", onClick: (row) => { setActiveReport(row); openModal("report-view-modal"); } },
    { icon: <Pencil size={14} />, tooltip: "Edit", variant: "primary", onClick: (row) => { setForm({ ...row }); openModal("report-form-modal"); } },
  ];

  // Form Input Helper
  const FormInput = ({ label, field, placeholder }) => (
    <div className="space-y-1.5">
      <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">{label}</label>
      <input type="text" value={form[field]} onChange={e => handleFormChange(field, e.target.value)}
        className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-[#2a465a] focus:outline-none focus:border-[#38bdf8] focus:ring-1 focus:ring-[#38bdf8] transition-all"
        placeholder={placeholder || `Enter ${label.toLowerCase()}`} />
    </div>
  );

  const FormSelect = ({ label, field, options }) => (
    <div className="space-y-1.5">
      <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">{label}</label>
      <select value={form[field]} onChange={e => handleFormChange(field, e.target.value)}
        className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-[#2a465a] focus:outline-none focus:border-[#38bdf8] focus:ring-1 focus:ring-[#38bdf8] transition-all">
        {options.map(o => <option key={o} value={o}>{o}</option>)}
      </select>
    </div>
  );

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <Heading primaryText="Reports" secondaryText="Command Center" size={12} />

      {/* ── Action Bar ── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 -mt-2">
        <p className="text-sm font-semibold text-slate-400">Monitor, review, and manage department reports.</p>
        <div className="flex items-center gap-2 flex-wrap">
          <button onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2.5 rounded-2xl text-sm font-bold text-[#2a465a] bg-white border border-slate-200 hover:bg-slate-50 hover:-translate-y-0.5 transition-all duration-200 active:scale-95">
            <FileDown size={16} /> Export All
          </button>
          <button onClick={() => { setForm({ ...defaultForm }); openModal("report-form-modal"); }}
            className="flex items-center gap-2 px-4 py-2.5 rounded-2xl text-sm font-bold text-white shadow-lg bg-[#2a465a] hover:bg-gradient-to-r hover:from-[#1e3a52] hover:to-[#2b5a7a] hover:shadow-xl hover:-translate-y-0.5 transition-all duration-200 active:scale-95">
            <Plus size={16} /> Create Report
          </button>
        </div>
      </div>

      {/* ── KPI Cards ── */}
      <DashGrid cols={12} gap={4}>
        <DashCard title="Total Reports" value={String(total)} icon={<FileText size={22} />} accentColor="#355872" size={3} />
        <DashCard title="Published" value={String(published)} icon={<CheckCircle size={22} />} accentColor="#22c55e" size={3} />
        <DashCard title="Pending Review" value={String(drafts)} icon={<Clock size={22} />} accentColor="#f59e0b" size={3} />
        <DashCard title="Critical" value={String(critical)} icon={<AlertCircle size={22} />} accentColor="#ef4444" size={3} />
      </DashGrid>

      {/* ── Analytics Charts ── */}
      <DashGrid cols={12} gap={4}>
        <GAreaChart title="Report Activity Trend" subtitle="Monthly breakdown"
          data={reportTrendData}
          areas={[
            { key: "published", label: "Published", color: "#22c55e" },
            { key: "draft", label: "Drafts", color: "#f59e0b" },
            { key: "scheduled", label: "Scheduled", color: "#3b82f6" },
          ]} size={8} height={260} />
        <GBarChart title="Department Reports" subtitle="Reports vs approved"
          data={deptReportData}
          bars={[
            { key: "reports", label: "Total", color: "#94a3b8" },
            { key: "approved", label: "Approved", color: "#2a465a" },
          ]} size={4} height={260} />
      </DashGrid>

      {/* ── Reports Table ── */}
      <DataTable
        title="Reports Directory"
        columns={columns}
        rows={reports}
        actions={tableActions}
        size={12} pageSize={10} searchable exportable exportFileName="reports-data"
        filters={[
          { title: "Department", key: "department", type: "toggle", options: ["Sales", "Finance", "Mgmt", "HR"] },
          { title: "Status", key: "status", type: "toggle", options: ["Published", "Draft", "Scheduled"] },
          { title: "Priority", key: "priority", type: "toggle", options: ["Normal", "Critical"] },
          { title: "Type", key: "type", type: "toggle", options: ["Sales", "Finance", "Executive"] },
        ]}
      />

      {/* ══ VIEW MODAL ═══════════════════════════════════════════════════════ */}
      <Modal id="report-view-modal" title="Report Details">
        {activeReport && (
          <div className="space-y-5">
            <div className="flex items-center gap-4 bg-slate-50 p-4 rounded-2xl border border-slate-100">
              <div className="w-14 h-14 rounded-2xl bg-[#2a465a] flex items-center justify-center text-white shadow-lg">
                <FileText size={24} />
              </div>
              <div>
                <p className="text-lg font-black text-[#2a465a]">{activeReport.title}</p>
                <p className="text-sm font-bold text-slate-500">{activeReport.id} • {activeReport.owner}</p>
              </div>
            </div>

            <div className="flex flex-wrap gap-2">
              {[
                { label: activeReport.status, cls: activeReport.status === "Published" ? "bg-emerald-50 text-emerald-600" : activeReport.status === "Scheduled" ? "bg-sky-50 text-sky-600" : "bg-amber-50 text-amber-600" },
                { label: activeReport.type, cls: "bg-slate-50 text-slate-600" },
                { label: activeReport.department, cls: "bg-indigo-50 text-indigo-600" },
                { label: activeReport.cadence, cls: "bg-fuchsia-50 text-fuchsia-600" },
                { label: activeReport.priority, cls: activeReport.priority === "Critical" ? "bg-rose-50 text-rose-600" : "bg-slate-50 text-slate-500" },
              ].map(b => (
                <span key={b.label} className={`rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-widest ${b.cls}`}>{b.label}</span>
              ))}
            </div>

            <div className="grid grid-cols-2 gap-4">
              {[
                { label: "Owner", val: activeReport.owner },
                { label: "Period", val: activeReport.period },
                { label: "Generated On", val: activeReport.generatedOn },
                { label: "Report ID", val: activeReport.id },
              ].map(({ label, val }) => (
                <div key={label}>
                  <span className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1.5">{label}</span>
                  <span className="text-[#2a465a] font-bold bg-white px-3 py-2.5 rounded-xl block border border-slate-100 text-sm">{val}</span>
                </div>
              ))}
            </div>

            <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5">
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Summary</p>
              <p className="text-sm font-semibold leading-relaxed text-slate-700">{activeReport.summary}</p>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
              <Button text="Close" variant="ghost" size={3} onClick={() => closeModal("report-view-modal")} />
              <Button text="Edit Report" variant="primary" size={3} onClick={() => {
                closeModal("report-view-modal");
                setForm({ ...activeReport });
                openModal("report-form-modal");
              }} />
            </div>
          </div>
        )}
      </Modal>

      {/* ══ CREATE/EDIT MODAL ═════════════════════════════════════════════════ */}
      <Modal id="report-form-modal" title={form.id ? "Edit Report" : "Create Report"}>
        <div className="space-y-4">
          <FormInput label="Report Title" field="title" />
          <div className="grid grid-cols-2 gap-4">
            <FormInput label="Owner" field="owner" />
            <FormInput label="Period" field="period" placeholder="e.g. Apr 2026" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <FormSelect label="Type" field="type" options={["Sales", "Finance", "Executive"]} />
            <FormSelect label="Department" field="department" options={["Sales", "Finance", "Mgmt", "HR"]} />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <FormSelect label="Cadence" field="cadence" options={["Daily", "Weekly", "Monthly", "Quarterly"]} />
            <FormSelect label="Status" field="status" options={["Draft", "Published", "Scheduled"]} />
          </div>
          <FormSelect label="Priority" field="priority" options={["Normal", "Critical"]} />
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Summary</label>
            <textarea value={form.summary} onChange={e => handleFormChange("summary", e.target.value)} rows={3}
              className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-semibold text-[#2a465a] focus:outline-none focus:border-[#38bdf8] focus:ring-1 focus:ring-[#38bdf8] transition-all resize-none"
              placeholder="Describe what this report covers" />
          </div>

          <div className="flex justify-end gap-3 pt-4 border-t border-slate-100 mt-6">
            <Button text="Cancel" variant="ghost" size={3} onClick={() => closeModal("report-form-modal")} disabled={isSubmitting} />
            <Button text={isSubmitting ? "Saving..." : form.id ? "Update" : "Create"} variant="primary" size={3}
              onClick={handleSave} disabled={isSubmitting || !form.title || !form.owner} />
          </div>

          {form.id && (
            <div className="flex items-center gap-3 pt-3 border-t border-slate-100 mt-2">
              <span className="text-xs font-bold text-rose-400 uppercase tracking-widest mr-auto">Danger Zone</span>
              <Button text="Delete Report" variant="danger" size={3} onClick={handleDelete} />
            </div>
          )}
        </div>
      </Modal>
    </div>
  );
}
