// FinanceDealsData.js — structured dummy data for Finance Deals workflow

export const financeDeals = [
  {
    id: "F-001",
    client: "Arjun Mehta",
    mobile: "9876543210",
    email: "arjun.mehta@solarkraft.in",
    salesExecutive: "Rahul Singh",
    serviceCategory: "Website",
    expectedBudget: 168000,
    priority: "High",
    status: "Interested",
    lastFollowUp: "2026-05-18",
    createdDate: "2026-05-05",
    date: "2026-05-05",
    nextFollowUpDate: "2026-05-22",
    missedFollowUp: false,
    prospectSummary: "Enterprise website with client portal, lead capture and analytics.",
    requirementId: "REQ-001",
    invoiceId: "INV-101",
    attachments: ["Requirement PDF", "Reference Images", "Signed Invoice"],
  },
  {
    id: "F-002",
    client: "Priya Sharma",
    mobile: "9823456789",
    email: "priya.sharma@brightmedia.com",
    salesExecutive: "Aarti Verma",
    serviceCategory: "SEO",
    expectedBudget: 85000,
    priority: "Medium",
    status: "Talk",
    lastFollowUp: "2026-05-16",
    createdDate: "2026-05-08",
    date: "2026-05-08",
    nextFollowUpDate: "2026-05-24",
    missedFollowUp: false,
    prospectSummary: "SEO and content support for product launch in Q3.",
    requirementId: "REQ-002",
    invoiceId: "INV-102",
    attachments: ["Proposal Doc", "Keyword Research"],
  },
  {
    id: "F-003",
    client: "TechNova Pvt Ltd",
    mobile: "9988776655",
    email: "contact@technova.in",
    salesExecutive: "Suresh Patel",
    serviceCategory: "CRM",
    expectedBudget: 320000,
    priority: "High",
    status: "Invoice Sent",
    lastFollowUp: "2026-05-17",
    createdDate: "2026-05-02",
    date: "2026-05-02",
    nextFollowUpDate: "2026-05-20",
    missedFollowUp: true,
    prospectSummary: "CRM implementation with sales automation and reporting.",
    requirementId: "REQ-003",
    invoiceId: "INV-103",
    attachments: ["CRM Scope PDF", "Signed Proposal"],
  },
  {
    id: "F-004",
    client: "Kavya Nair",
    mobile: "9012345678",
    email: "kavya@nair.com",
    salesExecutive: "Rahul Singh",
    serviceCategory: "Branding",
    expectedBudget: 45000,
    priority: "Low",
    status: "Confirmed",
    lastFollowUp: "2026-05-15",
    createdDate: "2026-05-01",
    date: "2026-05-01",
    nextFollowUpDate: "2026-05-01",
    missedFollowUp: false,
    prospectSummary: "Refresh brand identity for seasonal campaign.",
    requirementId: "REQ-004",
    invoiceId: "INV-104",
    attachments: ["Brand Kit", "Signed Invoice"],
  },
  {
    id: "F-005",
    client: "Rohan Gupta",
    mobile: "9812398123",
    email: "rohan@gupta.com",
    salesExecutive: "Aarti Verma",
    serviceCategory: "Mobile App",
    expectedBudget: 210000,
    priority: "High",
    status: "Not Interested",
    lastFollowUp: "2026-05-14",
    createdDate: "2026-05-09",
    date: "2026-05-09",
    nextFollowUpDate: "2026-05-09",
    missedFollowUp: false,
    prospectSummary: "Consumer app with login, payment gateway and dashboard.",
    requirementId: "REQ-005",
    invoiceId: "INV-105",
    attachments: ["App Brief", "Discovery Notes"],
  },
  {
    id: "F-006",
    client: "Meera Constructions",
    mobile: "9078563412",
    email: "accounts@meera.in",
    salesExecutive: "Suresh Patel",
    serviceCategory: "Social Media Marketing",
    expectedBudget: 62000,
    priority: "Medium",
    status: "Not Talk",
    lastFollowUp: "2026-05-12",
    createdDate: "2026-05-06",
    date: "2026-05-06",
    nextFollowUpDate: "2026-05-06",
    missedFollowUp: true,
    prospectSummary: "Social campaign for new residential project.",
    requirementId: "REQ-006",
    invoiceId: "INV-106",
    attachments: ["Campaign Brief", "Reference Images"],
  },
  {
    id: "F-007",
    client: "Ravi Logistics",
    mobile: "9845123789",
    email: "ravi@logisticspro.com",
    salesExecutive: "Aarti Verma",
    serviceCategory: "CRM",
    expectedBudget: 285000,
    priority: "High",
    status: "Interested",
    lastFollowUp: "2026-05-18",
    createdDate: "2026-05-10",
    date: "2026-05-10",
    nextFollowUpDate: "2026-05-23",
    missedFollowUp: false,
    prospectSummary: "CRM for operations tracking and client approvals.",
    requirementId: "REQ-007",
    invoiceId: "INV-107",
    attachments: ["Workflow Map", "Requirement PDF"],
  },
];

export const requirementForms = [
  {
    dealId: "F-001",
    status: "Interested",
    projectType: "Website",
    servicesRequired: ["UI Design", "Frontend", "Backend", "Hosting"],
    requirementDescription: "Client needs an enterprise website with a client portal, lead capture and analytics dashboard.",
    featuresNeeded: "Admin Panel, Login System, Payment Gateway, Dashboard",
    timeline: "6 weeks",
    estimatedBudget: "168000",
    priority: "High",
    internalNotes: "Deliver MVP before June end.",
    nextFollowUpDate: "2026-05-22",
    reason: "",
    conversationNotes: "",
  },
  {
    dealId: "F-002",
    status: "Talk",
    projectType: "SEO",
    servicesRequired: ["SEO", "Maintenance"],
    requirementDescription: "Improve organic rankings for upcoming product launch.",
    featuresNeeded: "Content Strategy, On-page SEO, Monthly Reports",
    timeline: "8 weeks",
    estimatedBudget: "85000",
    priority: "Medium",
    internalNotes: "Follow up with content team for keywords.",
    nextFollowUpDate: "2026-05-24",
    reason: "",
    conversationNotes: "Client wants ecommerce website with admin panel and requested quotation tomorrow.",
  },
  {
    dealId: "F-003",
    status: "Invoice Sent",
    projectType: "CRM",
    servicesRequired: ["Backend", "Maintenance", "Hosting"],
    requirementDescription: "CRM implementation for sales automation, lead scoring and reporting.",
    featuresNeeded: "Admin Panel, Dashboard, Reports, Automation Rules",
    timeline: "10 weeks",
    estimatedBudget: "320000",
    priority: "High",
    internalNotes: "Client wants integration with existing ERP.",
    nextFollowUpDate: "2026-05-20",
    reason: "",
    conversationNotes: "Invoice sent for review, waiting on final approval.",
  },
  {
    dealId: "F-004",
    status: "Confirmed",
    projectType: "Branding",
    servicesRequired: ["Branding", "Logo Design", "Social Media Marketing"],
    requirementDescription: "New brand identity and campaign design for seasonal launch.",
    featuresNeeded: "Brand Guidelines, Logo, Social Templates",
    timeline: "4 weeks",
    estimatedBudget: "45000",
    priority: "Low",
    internalNotes: "Client confirmed after proposal review.",
    nextFollowUpDate: "2026-05-01",
    reason: "",
    conversationNotes: "Confirmed project and signed agreement.",
  },
  {
    dealId: "F-005",
    status: "Not Interested",
    projectType: "Mobile App",
    servicesRequired: ["UI Design", "Frontend", "Backend"],
    requirementDescription: "App requirement discussed but client paused due to budget.",
    featuresNeeded: "Login System, Payment Gateway, Dashboard",
    timeline: "",
    estimatedBudget: "210000",
    priority: "High",
    internalNotes: "Revisit next quarter if budget opens up.",
    nextFollowUpDate: "2026-05-09",
    reason: "Budget issue",
    conversationNotes: "",
  },
  {
    dealId: "F-006",
    status: "Not Talk",
    projectType: "Social Media Marketing",
    servicesRequired: ["Branding", "SEO", "Maintenance"],
    requirementDescription: "Unable to reach client on provided number.",
    featuresNeeded: "Campaign Plan, Content Calendar",
    timeline: "",
    estimatedBudget: "62000",
    priority: "Medium",
    internalNotes: "Try alternate contact after 2 days.",
    nextFollowUpDate: "2026-05-06",
    reason: "Number unreachable",
    conversationNotes: "",
  },
  {
    dealId: "F-007",
    status: "Interested",
    projectType: "CRM",
    servicesRequired: ["UI Design", "Frontend", "Backend", "Hosting", "Maintenance"],
    requirementDescription: "CRM for logistics approvals, vendor portals and status tracking.",
    featuresNeeded: "Admin Panel, Dashboard, Login System, Reports",
    timeline: "9 weeks",
    estimatedBudget: "285000",
    priority: "High",
    internalNotes: "Request detailed vendor integration spec.",
    nextFollowUpDate: "2026-05-23",
    reason: "",
    conversationNotes: "",
  },
];

export const invoiceRecords = [
  {
    dealId: "F-001",
    invoiceNumber: "INV-101",
    clientName: "Arjun Mehta",
    services: "Website, Hosting",
    features: "Admin Panel, Login System, Payment Gateway, Dashboard",
    gst: "₹30,240",
    discount: "₹8,400",
    finalAmount: "₹189,840",
    terms: "Payment due within 15 days of invoice. 18% GST applies.",
    notes: "Awaiting client signature.",
    invoiceStatus: "Draft",
  },
  {
    dealId: "F-002",
    invoiceNumber: "INV-102",
    clientName: "Priya Sharma",
    services: "SEO, Maintenance",
    features: "Content Strategy, On-page SEO, Reporting",
    gst: "₹15,300",
    discount: "₹2,500",
    finalAmount: "₹82,800",
    terms: "Invoice payable within 10 days after approval.",
    notes: "Include monthly audit report.",
    invoiceStatus: "Draft",
  },
  {
    dealId: "F-003",
    invoiceNumber: "INV-103",
    clientName: "TechNova Pvt Ltd",
    services: "CRM, Hosting, Maintenance",
    features: "Admin Panel, Reports, Automation Rules",
    gst: "₹57,600",
    discount: "₹16,000",
    finalAmount: "₹361,600",
    terms: "Invoice sent, payment due in 30 days.",
    notes: "Follow up if payment not received by due date.",
    invoiceStatus: "Sent",
  },
  {
    dealId: "F-004",
    invoiceNumber: "INV-104",
    clientName: "Kavya Nair",
    services: "Branding, Logo Design",
    features: "Brand Guidelines, Social Templates",
    gst: "₹8,100",
    discount: "₹0",
    finalAmount: "₹53,100",
    terms: "Booking advance received. Remaining due on delivery.",
    notes: "Project confirmed and signed.",
    invoiceStatus: "Confirmed",
  },
  {
    dealId: "F-005",
    invoiceNumber: "INV-105",
    clientName: "Rohan Gupta",
    services: "Mobile App, UI Design",
    features: "Login System, Payment Gateway, Dashboard",
    gst: "₹37,800",
    discount: "₹10,500",
    finalAmount: "₹237,300",
    terms: "Proposal shared, no invoice issued.",
    notes: "Client paused due to budget.",
    invoiceStatus: "Draft",
  },
  {
    dealId: "F-006",
    invoiceNumber: "INV-106",
    clientName: "Meera Constructions",
    services: "Social Media Marketing",
    features: "Campaign Plan, Content Calendar",
    gst: "₹11,160",
    discount: "₹2,500",
    finalAmount: "₹70,660",
    terms: "Send follow-up when client is reachable.",
    notes: "Number unreachable.",
    invoiceStatus: "Draft",
  },
  {
    dealId: "F-007",
    invoiceNumber: "INV-107",
    clientName: "Ravi Logistics",
    services: "CRM, Hosting, Maintenance",
    features: "Dashboard, Login System, Reports, Admin Panel",
    gst: "₹51,300",
    discount: "₹12,000",
    finalAmount: "₹324,300",
    terms: "Draft invoice ready for client approval.",
    notes: "Awaiting vendor integration details.",
    invoiceStatus: "Draft",
  },
];

export const timelineHistory = [
  {
    dealId: "F-001",
    events: [
      { id: "H-001", event: "Prospect received from Sales", timestamp: "2026-05-05 10:12 AM" },
      { id: "H-002", event: "Initial call completed", timestamp: "2026-05-06 11:00 AM" },
      { id: "H-003", event: "Requirement form submitted", timestamp: "2026-05-18 04:28 PM" },
      { id: "H-004", event: "Invoice draft created", timestamp: "2026-05-19 09:20 AM" },
    ],
  },
  {
    dealId: "F-002",
    events: [
      { id: "H-005", event: "Prospect received from Sales", timestamp: "2026-05-08 09:05 AM" },
      { id: "H-006", event: "Client call scheduled", timestamp: "2026-05-12 02:30 PM" },
      { id: "H-007", event: "SEO scope agreed", timestamp: "2026-05-16 01:45 PM" },
    ],
  },
  {
    dealId: "F-003",
    events: [
      { id: "H-008", event: "Prospect received from Sales", timestamp: "2026-05-02 08:40 AM" },
      { id: "H-009", event: "Requirement capture completed", timestamp: "2026-05-09 10:50 AM" },
      { id: "H-010", event: "Invoice sent", timestamp: "2026-05-17 03:30 PM" },
      { id: "H-011", event: "Follow-up reminder added", timestamp: "2026-05-18 11:15 AM" },
    ],
  },
  {
    dealId: "F-004",
    events: [
      { id: "H-012", event: "Prospect received from Sales", timestamp: "2026-05-01 09:40 AM" },
      { id: "H-013", event: "Client confirmed branding scope", timestamp: "2026-05-05 12:20 PM" },
      { id: "H-014", event: "Invoice signed", timestamp: "2026-05-15 02:10 PM" },
    ],
  },
  {
    dealId: "F-005",
    events: [
      { id: "H-015", event: "Prospect received from Sales", timestamp: "2026-05-09 11:00 AM" },
      { id: "H-016", event: "Budget issue recorded", timestamp: "2026-05-14 03:22 PM" },
      { id: "H-017", event: "Deal marked not interested", timestamp: "2026-05-14 03:30 PM" },
    ],
  },
  {
    dealId: "F-006",
    events: [
      { id: "H-018", event: "Prospect received from Sales", timestamp: "2026-05-06 10:05 AM" },
      { id: "H-019", event: "Number unreachable", timestamp: "2026-05-12 01:10 PM" },
      { id: "H-020", event: "Follow-up call pending", timestamp: "2026-05-12 01:15 PM" },
    ],
  },
  {
    dealId: "F-007",
    events: [
      { id: "H-021", event: "Prospect received from Sales", timestamp: "2026-05-10 09:50 AM" },
      { id: "H-022", event: "Requirements reviewed", timestamp: "2026-05-18 05:00 PM" },
      { id: "H-023", event: "Invoice draft prepared", timestamp: "2026-05-19 10:05 AM" },
    ],
  },
];

export const followUpRecords = [
  { dealId: "F-001", date: "2026-05-18", notes: "Discussed portal workflows and milestone delivery.", type: "Call" },
  { dealId: "F-001", date: "2026-05-22", notes: "Reminder for contract approval.", type: "Email" },
  { dealId: "F-002", date: "2026-05-16", notes: "Reviewed SEO goals and monthly retainer.", type: "Call" },
  { dealId: "F-003", date: "2026-05-17", notes: "Invoice sent and approval requested from finance.", type: "Email" },
  { dealId: "F-004", date: "2026-05-15", notes: "Client confirmed branding scope and signed statement of work.", type: "Call" },
  { dealId: "F-005", date: "2026-05-14", notes: "Budget constraint noted; client paused discussion.", type: "Call" },
  { dealId: "F-006", date: "2026-05-12", notes: "Phone unreachable, alternate contact requested.", type: "Call" },
  { dealId: "F-007", date: "2026-05-18", notes: "Discussed vendor integrations and timeline.", type: "Call" },
];
